server:
  port: 9050
  servlet:
    context-path: /v1/poli
spring:
  datasource:
    max-lifetime: 6000
    driver-class-name : org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-83-137-206.compute-1.amazonaws.com:5432/d8ulnj17m5mv48
    platform: postgres
    username: ctplaaogvdwfvs
    password: 173d5c717946b23c764c69b53bbf5cfe50f72c703b5ae5e999f79b5bfcde4470
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
