server:
  port: 9050
  servlet:
    context-path: /poli/v1
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-194-171-47.compute-1.amazonaws.com:5432/dfhov4hlv7npbu
    username: eiyvedcktyvock
    password: 2f5859638d5f1b9f364d3b8dad32e1e92a7208fbf449da1aa499d39e6299c145
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

